# Railway Configuration for Hotel Management System
# This tells Railway how to build and deploy the application

[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "node src/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
