# Railway Configuration for Hotel Management System
# Use NIXPACKS builder since Dockerfile is in backend directory

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node src/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
